### ISSUE TITLE
Import DefaultAdapter is Plugin

### ISSUE THREAD

**Issue by ViktorPegy** [vuex-orm/plugin-graphql#109]
If we import default adapter type by
```
import DefaultAdapter from '@vuex-orm/plugin-graphql';
```
VSCode thinks it is `VuexORMGraphQL` from `dist/types/vuex-orm-graphql.d.ts`

Can we change `typings` property in `package.json` to `dist/types/index.d.ts` and move `VuexORMGraphQL` declaration inside?

**Comment by phortx** [comment]
VSCode is right, it should be

`import { DefaultAdapter } from '@vuex-orm/plugin-graphql';`

;)

**Comment by ViktorPegy** [comment]
![DeepinScreenshot_select-area_20190619124911](https://user-images.githubusercontent.com/9131850/59755502-abfde580-9290-11e9-8e53-8d09fb10f064.png)

with default `"typings": "dist/types/vuex-orm-graphql.d.ts"` is not working correct

**Comment by phortx** [comment]
Alright, that sounds plausible. Could you create a MR? :)

**Comment by ViktorPegy** [comment]
PR #110

**Comment by phortx** [comment]
Thanks! :)
