### ISSUE TITLE
issue with plain query using adapter

### ISSUE THREAD

**Issue by chan1di** [vuex-orm/plugin-graphql#111]
**Below is my setup that i tried to make the plain query work**

> const options = {
>   connectionQueryMode: 'plain',
>   // defaultOptions: {
>   //   watchQuery: {
>   //     fetchPolicy: 'cache-and-network'
>   //   ### }
>   // },
>   adapter: CustomAdapter,
>   database: database,
>   url: 'http://localhost:8503/',
>   includeExtensions: true,
>   debug: process.env.NODE_ENV !== 'production'
> }

**I want to generate the below query with " await Vuetest.fetch()" But when i call this i get query with 'NODE' mode instead of 'PLAIN' mode**

> query Vuetests {
>   vuetests {
>       id
>       personTwo
>       personOne
>       amount
>   }
> }

**Can anyone tell me what's wrong here? Is it the setup or is it something in the graphql-plugin**

**Without custom/Default adapter i get below node query** 
![Screenshot from 2019-06-27 06-41-18](https://user-images.githubusercontent.com/13073412/60225945-a878e880-98a6-11e9-8509-5ba86260cd5f.png)

**and with adapter i get the following error** 
![Screenshot from 2019-06-27 06-42-45](https://user-images.githubusercontent.com/13073412/60225977-ccd4c500-98a6-11e9-9fb2-3afe6209b3fc.png)

**Comment by phortx** [comment]
Can you show me the code of your custom adapter?

**Comment by chan1di** [comment]
##112 this solved my issue.. thanks a lot for quick reply. Glad to use this library
