### ISSUE TITLE
adapter.getRootQueryName is not a function

### ISSUE THREAD

**Issue by alexandrmiee** [vuex-orm/plugin-graphql#112]
I use CustomAdapter 
```js
import DefaultAdapter from '@vuex-orm/plugin-graphql'

export class CustomAdapter extends DefaultAdapter {
  static getConnectionMode () {
    return 'plain'
  }
}

VuexORM.use(VuexORMGraphQL, {
  database,
  debug: process.env.NODE_ENV !== 'production',
  adapter: CustomAdapter
})
```
And get error 
`r.adapter.getRootQueryName is not a function`

**Comment by phortx** [comment]
`import DefaultAdapter from '@vuex-orm/plugin-graphql'`

should be

`import `DefaultAdapter` from '@vuex-orm/plugin-graphql'`

**Comment by alexandrmiee** [comment]
Still get same error

**Comment by phortx** [comment]
Also `adapter: CustomAdapter` should be `adapter: new CustomAdapter`

**Comment by alexandrmiee** [comment]
Еhe error is gone, thanks!

But the connection mode has not changed
What can I do to set a “plan”?

**Comment by alexandrmiee** [comment]
Removed the “static” modifier from getConnection Mode, and now works

**Comment by zyonnetworks** [comment]
Hi, I have done this but get the following error
```

import { DefaultAdapter } from '@vuex-orm/plugin-graphql'

export class CustomAdapter extends DefaultAdapter {
  getConnectionMode () {
    return 'plain'
  }
}

VuexORM.use(VuexORMGraphQL, {
  database,
  // url
  debug: process.env.NODE_ENV !== 'production',
  adapter: new CustomAdapter()
})
```

```
Error: Can't determine the connection mode due to the fact that here are no connection types in the schema. Please set the connectionQueryMode via Vuex-ORM-GraphQL options!
```

**Comment by johnrix** [comment]
Documentation needs updating... I stumbled upon the same issue as above.

https://vuex-orm.github.io/plugin-graphql/guide/adapters.html#basics
