### ISSUE TITLE
Feature request: When persisting a new entity without an ID, get ID from GraphQL

### ISSUE THREAD

**Issue by oligus** [vuex-orm/plugin-graphql#116]
When creating a new entity with `create` or `insert`, the ID is not set unless you have an increment ID property type.

When persisting the newly created entity, you get the following error:
```
[Vue warn]: Error in v-on handler (Promise/async): "Error: The persist action requires the 'id' to be set"

vue.esm.js?efeb:1897 Error: The persist action requires the 'id' to be set
    at Function.eval (vuex-orm-graphql.es5.js?638b:1)
    at eval (vuex-orm-graphql.es5.js?638b:1)
    at Object.eval [as next] (vuex-orm-graphql.es5.js?638b:1)
    at eval (vuex-orm-graphql.es5.js?638b:1)
    at new Promise (<anonymous>)
    at __awaiter (vuex-orm-graphql.es5.js?638b:1)
    at Function.t.call (vuex-orm-graphql.es5.js?638b:1)
    at Array.wrappedActionHandler (vuex.esm.js?358c:721)
    at Store.dispatch (vuex.esm.js?358c:428)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?358c:322)
```

This is probably to be expected.

However in practical reality, you might want to create the entity on the server first, and if successful, get the ID from the server creation and THEN create the entity on the Vuex-ORM, to be in sync.

This way, you can have a seamless developer experience with Vuex-ORM visavi GraphQL.

You create an entity
You persist it
The entity instance is now available via ORM

**Comment by phortx** [comment]
Hi,

thanks for the report.

This should already work, when you have an auto increment. Then you get the ID from the server.

However, the case without auto increment seems not work. Can you send me your model definition?

**Comment by oligus** [comment]
Thank you for fast response.

I might be missing something here, so let me see if I understand this correctly

*Given we do not have increment ID property*
Error will be rendered about missing ID, no other action is taken

*Given we do have increment ID property*
It works but it does just take the last ID + 1 using the increment. So in my case, the last entity from the server has ID 15, if I create a new one this will have ID 16 as decided by the Vuex-ORM. After this the entity is created via GraphQL.

Model:
```js
import { Model } from '@vuex-orm/core'

class LicensePackageCategoriesModel extends Model {
  static entity = 'licensePackageCategories'

  static fields () {
    return {
      id: this.number(), // increment()
      name: this.string(''),
      description: this.string(''),
      nameEnglish: this.string(''),
      descriptionEnglish: this.string('')
    }
  }
}

export default LicensePackageCategoriesModel
```

Persist:
```js
await LicensePackageCategoriesModel.insert({ data })
const category = LicensePackageCategoriesModel.query().last()
category.$persist()
```

**Comment by oligus** [comment]
No, this works fine, I'm just not testing completely, sorry for this!

**Comment by phortx** [comment]
:D No problem
