### ISSUE TITLE
Out of sync with latest vuex-orm

### ISSUE THREAD

**Issue by curbol** [vuex-orm/plugin-graphql#142]
It looks like this hasn't been updated if over 9 months and now has some compatibility issues with the latest version of vuex-orm. Is this project still being maintained?

**Comment by phortx** [comment]
You're right, I haven't been active the last year for private reasons. But now I'm back :) I will update the plugin as soon as possible :)

**Comment by phortx** [comment]
The current master branch now is compatible with latest vuex-orm.

I will do some tests and release it as soon as possible :)
