### ISSUE TITLE
Need to change the "typings" path to "dist/index.d.ts"

### ISSUE THREAD

**Issue by icetomcat** [vuex-orm/plugin-graphql#158]
https://github.com/vuex-orm/plugin-graphql/blob/bd1ffc7e714dc14b886bbe693ab716e1c0b67ed8/package.json#L9

**Comment by timvandesteeg** [comment]
Any progress or workaround on this? This little typo is causing our Jest tests not to run.
Loving the plugin by the way.

**Comment by phortx** [comment]
Should be fixed with https://github.com/vuex-orm/plugin-graphql/releases/tag/v1.0.0-rc.42
