### ISSUE TITLE
v1.0.0-rc.42 not published to NPM?

### ISSUE THREAD

**Issue by jimmiejackson414-zz** [vuex-orm/plugin-graphql#165]
Hi there! Just getting started with this plugin, I've been a huge fan of the vuex-orm library for awhile (previously used the axios-plugin). Running into some issues installing into an existing Nuxt app, and I'm hoping that rc.42 will fix it, however it doesn't appear to be published to NPM yet. The latest I see is rc.41.

**Comment by phortx** [comment]
Wow, good point! Just forgot about this 🙈 

https://www.npmjs.com/package/@vuex-orm/plugin-graphql/v/1.0.0-rc.42

here it is. Sorry!
