### ISSUE TITLE
Incorrect type for registration within VuexORM

### ISSUE THREAD

**Issue by loe-lobo** [vuex-orm/plugin-graphql#44]
Hello.

I'm trying to use this plugin but when I try to register it in VuexORM the type of VuexORMGraphQL is not Plugin.

```
import VuexORM from '@vuex-orm/core';

Vue.use(Vuex);

const database = new VuexORM.Database();

database.register(Answer, answers);
database.register(Question, questions);

import VuexORMGraphQL from '@vuex-orm/plugin-graphql';
VuexORM.use(VuexORMGraphQL, { database });

```

```
Argument of type 'typeof VuexORMGraphQLPlugin' is not assignable to parameter of type 'Plugin'.
  Types of property 'install' are incompatible.
    Type '(components: Components, options: Options) => VuexORMGraphQL' is not assignable to type '(components: Components, options: Options) => void'.
      Types of parameters 'options' and 'options' are incompatible.
```

**Comment by phortx** [comment]
I've have the exact same setup in my project with current versions and it works.

But yesterday I've tried to setup jest tests and had a similar problem 🤔 

Could you please tell me which versions of Vue, Vuex, Vuex-ORM and Vuex-ORM-GraphQL you're using?

@kiaking Do you have any idea?

**Comment by phortx** [comment]
PPS: Of course you're working with TS, the error message is clearly from TS.

The reason is, that the Plugin class doesn't implement the `Plugin` interface of Vuex-ORM. I will fix that. :)

**Comment by loe-lobo** [comment]
Sorry for not adding all the information in the first message.
Yes, I'm using TS and the issue is exactly what you said, the plugin does not implements `Plugin` from Vuex-ORM.

Thank you for your prompt response =)

**Comment by phortx** [comment]
No problem at all!

I've tried to implement the Plugin interface, but I think the interface is wrong 🤔 I'm talking with @kiaking to resolve that issue.

Stay tuned!

**Comment by phortx** [comment]
Currently not. I have to wait for @kiaking who wanted to check the probably wrong Plugin interface in the Vuex-ORM source code.

@kiaking Anything new here?

**Comment by kiaking** [comment]
Oops! Sorry I'll take a look and fix it! Just a moment.

**Comment by phortx** [comment]
@kiaking is this fixed meanwhile? :)
