### ISSUE TITLE
Load relationships on demand

### ISSUE THREAD

**Issue by oligus** [vuex-orm/plugin-graphql#46]
Currently, all relational data is fetched eagerly.

This could potentially be a problem with related data that has vast amount of records. It is probably not always desirable to fetch `all` relational data of the parent model.

it would be great if we it were possible to somehow define what related data you want to fetch for that particular request.

**Comment by phortx** [comment]
I could imagine, that the `fetch()` method accepts a `include` param with a list of relationships to eager load for that request. Could be useful.

**Comment by oligus** [comment]
Also consider relations och relations.

For instance, `MusicUsageAreasModel -> hasMany(PriceListsModel) -> hasMany(PricePriceRowsModel)`

You might want to to eager load`priceRows` or perhaps not.

`await MusicUsageAreasModel.fetch({ include: priceLists, priceLists.priceRows] })`

**Comment by gotexis** [comment]
How to combine queries to API?

Let's say we have Posts, Authors, and Comments.

Currently I have to do 3 queries:

Posts.fetch()
Comments.fetch()
Users.fetch()

Of course that is not optimal.

Plus when I bind fetch() to created(), 

everytime the is re-navigate to the page, the server is queried 4 times, once again.

**Comment by phortx** [comment]
@gotexis you can use eager loading to achieve that. See the docs. This way you could just fetch the Post and all related records are fetched within one query.

https://vuex-orm.github.io/plugin-graphql/guide/eager-loading.html

**Comment by dmitry** [comment]
@phortx that's done on the model level, not on the query level (via `fetch` method). Would be great to control it more finely, on the `fetch` level.

**Comment by phortx** [comment]
@dmitry Absolutely!

**Comment by phortx** [comment]
Moved to https://github.com/vuex-orm/plugin-graphql/issues/95
