### ISSUE TITLE
Mistaken `clone` function behaviour in QueryBuilder.buildQuery method on `src` version

### ISSUE THREAD

**Issue by mayoujin** [vuex-orm/plugin-graphql#47]
`Clone` methods in [dist/vuex-orm-graphql.esm.js](https://github.com/vuex-orm/vuex-orm-graphql/blob/31b69e12ebb4c7bb51643997dc1feda1434f1406/dist/vuex-orm-graphql.esm.js#L28127) version and [src/graphql/query-builder.ts](https://github.com/vuex-orm/vuex-orm-graphql/blob/31b69e12ebb4c7bb51643997dc1feda1434f1406/src/graphql/query-builder.ts#L109) have different behaviours. It is probably the wrong behaviour in [src/graphql/query-builder.ts](https://github.com/vuex-orm/vuex-orm-graphql/blob/31b69e12ebb4c7bb51643997dc1feda1434f1406/src/graphql/query-builder.ts#L109) which causes the argument `arg` property's value undesirable override in mutation.

Example
```
args = {
  id: '123',
  post: {
    title: 'Title'
  }
}

// after QueryBuilder.buildQuery('mutation', model, 'post', args, multiple, filter) call becomes

args = {
  id: '123',
  post: {
    __type: 'Post'
  }
}

```

All data inside `post` (`{ title: 'Title' }`) overrides with value ` { __type: 'Post' }`

**Comment by phortx** [comment]
I have written a test for this:

```js
    const args = {
      id: '123',
      post: {
        title: 'Title'
      }
    };

    let query = QueryBuilder.buildQuery('query', context.getModel('comment'), null, args, true, true);

    expect(args).toEqual({
      id: '123',
      post: {
        title: 'Title'
      }
    });
```

It's green. 

Could you pleas verify if I understood you and we are talking about the same? :)

**Comment by phortx** [comment]
I'll close this due to the lack of a response. If the issue still exists, please reopen it :)

Thanks
