### ISSUE TITLE
Allow use on server side/nuxt

### ISSUE THREAD

**Issue by andruu** [vuex-orm/plugin-graphql#49]
Is there any plans to allow this plugin to work serverside or with nuxt?

**Comment by phortx** [comment]
Hi!

Currently not, but out of the simple reason, that I don't have any nuxt apps currently where I work with this plugin. So I'm not even sure what's necessary to support SSR.

I'm very open for Pull Requests and if you could outline what requirements SSR has for this plugin, you would bring us a step further to SSR support :)

Thank you very much!

**Comment by NightFury2** [comment]
@phortx how to use in development mode using hot reloading?

**Comment by phortx** [comment]
@NightFury2 Nothing special to consider here :)

**Comment by phortx** [comment]
https://github.com/vuex-orm/plugin-graphql/releases/tag/v1.0.0-rc.21 brings experimental SSR support.

**Comment by phortx** [comment]
I close this due to the fact that SSR support is implemented. Bugs are new issues.
