### ISSUE TITLE
Dist files are very large

### ISSUE THREAD

**Issue by colinfindlay-nz** [vuex-orm/plugin-graphql#64]
Is there any reason that the final dist files are so large? (905Kb) - it's significantly larger than vuex-orm!
It looks like all the devDependencies have been included in the build... unless I'm reading it wrong.

**Comment by phortx** [comment]
Oh shit, yes this is way larger then it have to be. I will take a look!

**Comment by phortx** [comment]
This is fixed with version 1.0.0 RC 22.
