### ISSUE TITLE
Using import and require blocks usage of rollup

### ISSUE THREAD

**Issue by mario-minati** [vuex-orm/plugin-graphql#67]
The code uses import and require statements at the same time. Thus we cannot use rollup to bundle a vue project with vuex, vuex-orm, vuex-orm-graphql.

This seems to be a known problem and is documented here: #rollup/rollup#1058

**Comment by phortx** [comment]
Good to know! I'm working on a big refactoring and will try to fix this while doing that. Thanks for reporting.

**Comment by mario-minati** [comment]
I solved it through switching to webpack for the time being. Anyhow looking forward for the refactoring with less memory footprint. :-)

**Comment by phortx** [comment]
This is fixed with version 1.0.0 RC 22.
