### ISSUE TITLE
Creating relations without Id field

### ISSUE THREAD

**Issue by MLDMoritz** [vuex-orm/plugin-graphql#74]
My backend doesn't return the ids of the relations out of the box. 

This should work:

```js
color: this.hasOne(Color, 'color'),
```

It should fetch the relation from the color.id field.

Current behavior is that it's simply not working.

**Comment by kevrat** [comment]
Same. I have:

```graphql
type Action implements INode {
  id: ID! @id
  sportsman: Sportsman!
}
type Sportsman implements INode {
  id: ID! @id
}
```
And i don't have any sportsmanId in my schema.
How can i make relation?

Action model
```js
import { Model } from '@vuex-orm/core'

import Sportsman from '../sportsman/model'

export default class Action extends Model {
  static entity = 'actions'

  static fields () {
    return {
      id: this.attr(null),
      sportsman: this.belongsTo(Sportsman, '??')
    }
  }
}
```

Sportsman model 
```js
import { Model } from '@vuex-orm/core'

export default class Sportsman extends Model {
  static entity = 'sportsmen'

  static fields () {
    return {
      id: this.attr(null)
    }
  }
}

```

Maybe with Accessors/virtual field?

**Comment by phortx** [comment]
I think that's currently not possible, but with the new adapter pattern we can add support for this by adding an adapter hook. Something like `getRelationId` or something ... 

I will investigate on this after the next release.

**Comment by phortx** [comment]
@kevrat First of all, you have to have a foreign key (`sportmanId`). Vuex-ORM requires that.

Regarding the plugin-graphql, I'm trying to provide a fallback solution, which automatically reads the ID from the associated record: https://github.com/vuex-orm/plugin-graphql/pull/97

**Comment by phortx** [comment]
lol while implementing this, I discovered, that this should already work.

You need a foreign key field, because Vuex-ORM requires it, but it hasn't to be included in the schema. This plugin will then just ignore it and Vuex-ORM will use the id from the related record.

@kevrat could you try this?

**Comment by kevrat** [comment]
50/50 it's correct insert, but i can't query this later
![image](https://user-images.githubusercontent.com/9952048/57354170-8353dd80-7173-11e9-8222-86c193c7d42a.png)

ActionModel
```js
import uuid from 'uuid/v4'

import { Model } from '@vuex-orm/core'

import Sportsman from '../sportsman/model'
import Day from '../day/model'

export default class Action extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'actions'

  static fields () {
    return {
      id: this.attr(uuid()),
      sportsman: this.belongsTo(Sportsman, 'sp_id'),
      day: this.belongsTo(Day, 'day_id'),
      brigade: this.attr(''),
      // sportsman_id: this.attr(null),
      day_id: this.attr(null),
      mainNumber: this.number(0)
    }
  }
}
```

SportsmanModel
```js
import { Model } from '@vuex-orm/core'

// import Action from '../action/model'

export default class Sportsman extends Model {
  // This is the name used as module name of the Vuex Store.
  static entity = 'sportsmen'

  static fields () {
    return {
      id: this.attr(null),
      firstName: this.attr('')
      // actions: this.hasMany(Action, 'sportsmanId')
    }
  }
}

```

**Comment by phortx** [comment]
I'm not sure that this is related to the graphql-plugin. When the insert is correct, that could be an issue with the vuex-orm core.

@kiaking Any idea?

**Comment by kiaking** [comment]
I'm assuming the issue is `sportsman` is `null`. Maybe because Action model doesn't have foreign key specified at `sportsman` field?

```js
export default class Action extends Model {
  static entity = 'actions'

  static fields () {
    return {
      id: this.attr(uuid()),
      sportsman: this.belongsTo(Sportsman, 'sp_id'),
      day: this.belongsTo(Day, 'day_id'),
      brigade: this.attr(''),
      sp_id: this.attr(null), // <- I think you need this.
      day_id: this.attr(null),
      mainNumber: this.number(0)
    }
  }
}
```

**Comment by kevrat** [comment]
Yes, with this it works. I know it.
But i think issue is - how to make working relations without using sportsman_id field, if i only have sportsman field already in my graphql schema.
So, how to make it working with this schema:

```graphql
type Action{
  id: ID! @id
  sportsman: Sportsman!
}

type Sportsman{
  id: ID! @id
  firstName: String
}
```

It is responsibility of orm-core or it can be done on graphql-plugin side?

**Comment by kiaking** [comment]
@kevrat You must always have field that contains foreign key. Without it, Vuex ORM would have no idea how 2 models are related. However, you don't have to pass foreign key value when inserting data as long as you are passing data in nested format.

For example, you can pass following data:

```js
// Action records.
{
  id: 1,
  sportsman: {
    id: 1,
    firstName: 'John'
  }
}
```

Then, Vuex ORM will automatically generate `sportsman_id` value of 1 at Action model. But you must define `sportsman_id` field in your model, because Vuex ORM will strip off any field which is not present in model fields definition.

**Comment by phortx** [comment]
Correct. You don't need the foreign key field in your graphql schema (plugin graphql ignores it then), but you need it in your model definition.

**Comment by kevrat** [comment]
Thanks, it works!
I removed the sportsman_id from the schema, but left the sportsman_id as a foreign key in the model.
That way, I can get the associated data from the server and then request it from orm as if it were in the schema.
Maybe add a few words about this in the documentation?
I think it should be closed

**Comment by phortx** [comment]
Very nice, thanks :)

**Comment by creaux** [comment]
I think this should be in the documentation! It was a bit of pain to find it 🥇
