### ISSUE TITLE
Plugin has an opinion on naming conventions

### ISSUE THREAD

**Issue by gotexis** [vuex-orm/plugin-graphql#81]
Just started and have some trouble getting my first query done.

```js
async mounted() {
      // Load all users from the server
      await User.fetch();
    },
```

exception: Couldn't find Type of name Query in the GraphQL Schema.

```javascript
Uncaught (in promise) Error: Couldnt find Type of name Query in the GraphQL Schema.
    at e.getType (vuex-orm-graphql.es5.js?8eb2:1)
    at new e (vuex-orm-graphql.es5.js?8eb2:1)
    at eval (vuex-orm-graphql.es5.js?8eb2:1)
    at eval (vuex-orm-graphql.es5.js?8eb2:1)
    at Object.eval [as next] (vuex-orm-graphql.es5.js?8eb2:1)
    at a (vuex-orm-graphql.es5.js?8eb2:1)
```

**Comment by gotexis** [comment]
it seems that root mutation must be called "Mutation" and root query must be called "Query".

That solved the problem... I wish there were some documentations regarding this.

**Comment by gotexis** [comment]
further, it seems my 'listing' shall be called 'listings'

**Comment by gotexis** [comment]
Just wondering if there are better ways to get things done

**Comment by phortx** [comment]
> it seems that root mutation must be called "Mutation" and root query must be called "Query".
> That solved the problem... I wish there were some documentations regarding this.

I thinks that's the standard way to setup a GraphQL Schema. However, I think we could document the naming conventions in the docs :)

**Comment by phortx** [comment]
Should be solved with https://github.com/vuex-orm/plugin-graphql/pull/89

**Comment by phortx** [comment]
Merged (but not released yet)
