### ISSUE TITLE
Use plugin-graphql with SSR

### ISSUE THREAD

**Issue by mbajur** [vuex-orm/plugin-graphql#92]
Hello, I'm trying to use plugin-graphql with fresh nuxt.js app but details about that are not sufficient. I can see in FAQ that i need to use node-fetch and `global.fetch = fetch` but where exactly should i put that? In the store file definition? So far, my `store/index.js` looks as follows:

```
import VuexORM from '@vuex-orm/core'
import VuexORMGraphQL from '@vuex-orm/plugin-graphql'
import database from '~/db'
import fetch from 'node-fetch'

global.fetch = fetch

VuexORM.use(VuexORMGraphQL, { database })

export const plugins = [VuexORM.install(database)]
```

but app freezes (loading till infinity) when i'm trying to reach it in browser. Any tips much appreciated!

I'm using `plugin-graphql ^1.0.0-rc.33`

**Comment by phortx** [comment]
Hi!

My `store/index.js`:

```js
import Vuex from 'vuex';
import VuexORM from '@vuex-orm/core';
import VuexORMGraphQL from '@vuex-orm/plugin-graphql';
import { HttpLink } from 'apollo-link-http';
import database from './database';
import fetch from 'node-fetch';

const options = {
  database,
  debug: process.env.NODE_ENV === 'development' && process.client,
  url: process.env.BACKEND_URL + '/api/v2',
};

if (process.server) {
  options.link = new HttpLink({ uri: options.url, fetch });
}

VuexORM.use(VuexORMGraphQL, options);


export default function createStore () {
  const plugins = [VuexORM.install(database)];
  return new Vuex.Store({ plugins });
}
```

Seems you're right, setting `global.fetch` is deprecated and probably doesn't work. I've simply setup a HttpLink instance and pass fetch. I will update the docs :)

Please let me know if this fixes your problem.

**Comment by mbajur** [comment]
That was it! Thank you :)

**Comment by phortx** [comment]
Nice, I'll update the docs :)

**Comment by phortx** [comment]
Done.

**Comment by renestalder** [comment]
Work like a charm. Don't you think it would be worth adding this as a separate page into the documentation (or at least to the setup page) instead of only the F.A.Q? SSR is quite a fundamental part of modern web applications and it took me quite some time finding this issue here for the concrete solution.

**Comment by phortx** [comment]
That's exactly what I have done 😎 

https://github.com/vuex-orm/plugin-graphql/blob/master/docs/guide/nuxt.md

It's just not deployed yet :)

**Comment by renestalder** [comment]
🆒 🆒 🆒 :)

**Comment by canhkieu** [comment]
I can not use fetch, customQuery or customMutate on Nuxt. Any one same?
https://github.com/vuex-orm/plugin-graphql/issues/134

**Comment by codeturn** [comment]
> That's exactly what I have done 😎
> 
> https://github.com/vuex-orm/plugin-graphql/blob/master/docs/guide/nuxt.md
> 
> It's just not deployed yet :)

Hi. At this example you put check on process.server in plugin. And here this value will be always true. On client too. If make init is store as you show here: https://github.com/vuex-orm/plugin-graphql/issues/92#issuecomment-487260474 then process.server is right value.
